const questions = [
  ['clarity','Clareza do serviço','Quando alguém encontra sua empresa, entende rapidamente o que vocês fazem?','Pense em uma pessoa que ainda não conhece seu trabalho.'],
  ['region','Região atendida','Fica claro onde vocês atendem?','A região pode ajudar a pessoa a saber se faz sentido iniciar uma conversa.'],
  ['proof','Provas reais','Existe algo que ajude uma pessoa a confiar antes do primeiro contato?','Pode ser trabalho real autorizado, processo explicado, avaliações reais ou informações consistentes.'],
  ['contact','Caminho de contato','Uma pessoa sabe qual é o próximo passo para pedir informação ou orçamento?','Contato não é apenas ter um número: é deixar claro o que fazer depois.'],
  ['consistency','Coerência da presença','As informações principais parecem coerentes entre seus canais?','Nome, serviço, região e contato deveriam contar a mesma história onde a empresa aparece.']
];
const answers = [['sim','Sim, fica claro','A informação é fácil de identificar.'],['partial','Em parte','Ela existe, mas pode exigir procura ou interpretação.'],['no','Não sei ou não','Pode haver uma dificuldade antes da conversa.']];
const results = {
  clarity:['Clareza do serviço','O primeiro ponto a revisar pode ser como sua empresa explica, em poucos segundos, o que faz e para quem faz.',['Nome e serviço principal','Explicação simples do que vocês resolvem','Próximo passo para conversar']],
  region:['Região atendida','Pode valer revisar se cidade, bairros ou área de atendimento aparecem de forma fácil onde uma pessoa procura pela empresa.',['Local ou área atendida','Informação coerente nos canais','Contato adequado para a região']],
  proof:['Confiança antes do contato','O primeiro ajuste pode estar em organizar provas reais ou informações que ajudem a pessoa a entender melhor o trabalho antes de iniciar uma conversa.',['Trabalhos ou informações reais','Contexto do serviço','Forma simples de confirmar confiança']],
  contact:['Caminho até o contato','Seu ponto inicial pode ser tornar o próximo passo mais visível: a pessoa precisa saber o que fazer quando decide conversar.',['Contato fácil de localizar','Convite claro para a ação','Informação necessária para começar']],
  consistency:['Coerência entre os canais','Pode ser útil conferir se nome, serviço, região e contato contam a mesma história no Google, Instagram, site ou outros pontos públicos.',['Nome e informações essenciais','Serviço e região consistentes','Caminho de contato igual e atualizado']]
};
const stage=document.querySelector('[data-question-stage]'),result=document.querySelector('[data-result]'),label=document.querySelector('[data-progress-label]'),bar=document.querySelector('[data-progress-bar]'),resets=document.querySelectorAll('[data-reset]'),link=document.querySelector('[data-whatsapp-link]');let current=0,answersByKey={};
function renderQuestion(){const [key,category,title,copy]=questions[current];stage.hidden=false;result.hidden=true;label.textContent=`Pergunta ${current+1} de ${questions.length}`;bar.style.width=`${((current+1)/questions.length)*100}%`;stage.innerHTML=`<p class="question-label">${category}</p><h3 class="question-title">${title}</h3><p class="question-copy">${copy}</p><div class="answer-list">${answers.map(([value,text,detail])=>`<button class="answer" type="button" data-answer="${value}">${text}<small>${detail}</small></button>`).join('')}</div>`;stage.querySelectorAll('[data-answer]').forEach(button=>button.addEventListener('click',()=>{answersByKey[key]=button.dataset.answer;current++;current<questions.length?renderQuestion():renderResult()}))}
function renderResult(){const priority=['clarity','region','proof','contact','consistency'].find(key=>answersByKey[key]==='no')||['clarity','region','proof','contact','consistency'].find(key=>answersByKey[key]==='partial')||'consistency';const [title,copy,path]=results[priority];stage.hidden=true;result.hidden=false;label.textContent='Revisão concluída';bar.style.width='100%';document.querySelector('[data-result-title]').textContent=title;document.querySelector('[data-result-copy]').textContent=copy;document.querySelector('[data-result-path]').innerHTML=path.map(item=>`<span>${item}</span>`).join('');link.href=`https://wa.me/51980109047?text=${encodeURIComponent(`Fiz o Diagnóstico de Presença Digital. Meu primeiro ponto de revisão parece ser: ${title}. Quero entender qual pode ser o próximo passo para minha empresa.`)}`;resets.forEach(button=>button.hidden=false)}
function reset(){current=0;answersByKey={};resets.forEach(button=>button.hidden=true);renderQuestion()}resets.forEach(button=>button.addEventListener('click',reset));renderQuestion();
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.14});document.querySelectorAll('.reveal').forEach(element=>observer.observe(element));
